=== grizzly100/contraband/src/main/resources/schema/recordingSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "title": "Recording",
  "description": "A recording of a gig",
  "type": "object",
  "properties": {
    "id": {
      "description": "The unique identifier for a recording",
      "type": "string",
      "$comment": "example, 1982-07-10 - Zig Zag Club, London (V1 AUD)"
    },
    "artist": {
      "description": "The name of the artist",
      "type": "string",
      "$comment": "e.g., The Sisters of Mercy"
    },
    "date": {
      "description": "The date of the recording",
      "type": "string",
      "format": "date"
    },
    "additionalDates": {
      "description": "Additional dates if the recording is a compilation",
      "type": "array",
      "items": {
        "type": "string",
        "format" : "date"
      }
    },
    "source": {
      "description": "The source of the recording - audience (AUD) or mixing desk (SBD)",
      "type": "string",
      "enum" : [ "AUD", "SBD"]
    },
    "generation": {
      "description": "The generation of source tape or mix - M0 (clone), M1, M1-2, MX (mix), MX2 (mix 2)",
      "type": "string",
      "$comment": "M1-2 == gen 1 or 2; MX2 = 2nd mix (if more than one mix exist); ML = lossy",
      "pattern": "^M(X)?([0-9])?(-[0-9])?(L)?$"
    },
    "venue": {
      "description": "The venue (club, building, festival) that the gig took place",
      "type": "string",
      "$comment": "example, Zig Zag Club"
    },
    "location": {
      "description": "The location (city or town) of the recording",
      "type": "string",
      "$comment": "example, London"
    },
    "origin": {
      "description": "Origin of the recording, bootleg name or tape owner",
      "type": "string",
      "$comment": "example, Disguised In Black CD, or DJONES, KENDRIK, CIMMINO"
    },
    "version": {
      "description": "The version of the recording or vinyl rip",
      "type": "string",
      "pattern": "^V[0-9]+$",
      "$comment": "example, V1, V2, V3"
    },
    "resolution": {
      "description": "The bits-per-sample (bit depth) and sample rate (KHz) of the lossless audio",
      "type": "string",
      "pattern": "^([0-9]{2}) ([0-9]{2})$",
      "$comment": "Use for lossless, examples 16 44 or 24 96 - common depths 16, 24 bit & sample rates 44, 48, 96 KHz"
    },
    "bitrate": {
      "description": "The constant (CBR) or maximum variable (VBR) bit-rate kbps of the lossy audio",
      "type": "string",
      "pattern": "^([0-9]{2,4})$",
      "$comment": "Use for lossy, common bit rates include 96, 128, 256, 320, 1411"
    },
    "quality": {
      "description": "Subjective quality on scale of 1 to 5, or range e.g., 4-5",
      "type": "string",
      "pattern": "^([0-9])(-[0-9])?$",
      "$comment": "example, 3-4, 4, 4-5, 5"
    },
    "setlist": {
      "description": "Songs played",
      "type": "array",
      "items": {
        "type": "string"
      },
      "$comment": "example, ANACONDA"
    },
    "notes": {
      "description": "Any further notes on the recording",
      "type": "string",
      "$comment": "example, mix fixes cut in Alice by patching in 5secs from V2"
    }
  },
  "required": ["id", "artist", "date", "version"],
  "additionalProperties": false
}

=== grizzly100/contraband/target/test-classes/examples/info.json
{
  "id": "1982-07-10 - Zig Zag Club, London (V1 AUD)",
  "artist" : "The Sisters Of Mercy",
  "date": "1982-07-10",
  "version": "V99",
  "source": "AUD",
  "generation": "MX",
  "resolution": "16 96",
  "venue": "Zig Zag Club",
  "location": "London",
  "origin": "DJONES",
  "quality": "3-4",
  "setlist": ["ALICE","FLOORSHOW","WATCH","ADRENOCHROME","LIGHTS","1969","SISTER RAY"],
  "notes" : "nice"
}
